version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Australia/Sydney"
    groups:
      prod-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch