[release]
download_release_url = ""

[api]
update_interval_mins = 60

# darwin = "qvv117"
# sydney = "r3gx2f"
# melbourne = "r1r0fs"
# brisbane = "ynGBTJ"
# perth = "r28ekz"
# adelaide = "r1f93c"
# hobart = "r22u0d"
# canberra = "r3dp32"
# tasmania-cold = "r283sf"
location = "r22u0d" # uses GeoHash, must be 6 characters

# supproted colors = [black, white, green, blue, red, yellow, orange]
[colours]
background_colour = "white"
text_colour = "black"
x_axis_colour = "black"
y_left_axis_colour = "red"
y_right_axis_colour = "blue"
temp_colour = "red"
feels_like_colour = "green"
rain_colour = "blue"

[misc]
temp_unit = "C"
store_local = true
store_local_path = "./apis/"
template_path = "dashboard-template-min.svg"
modified_template_name = "dashboard.svg"
icon_path = "static/fill-svg-static/"
use_moon_phase_instead_of_clear_night = true
use_online_data = true                         # for debugging purposes
download_release_url = "https://github.com/mt-empty/pi-inky-weather-epd/releases/latest/download/x86_64-unknown-linux-gnu.zip"
