[release]
download_release_url = ""

[api]
update_interval_mins = 60
location = "r283sf"
use_online_data = false

[colours]
background_colour = "grey"
text_colour = "black"
x_axis_colour = "#74838f"
y_left_axis_colour = "#1f5079"
y_right_axis_colour = "#1b69a8"
temp_colour = "#ff0000"
feels_like_colour = "#00ff00"
rain_colour = "#0000ff"

[misc]
store_local = true
store_local_path = "./apis/"
template_path = "dashboard-template-min.svg"
modified_template_name = "dashboard.svg"
modified_template_dir_path = "../"
icon_path = "static/fill-svg-static/"
unit = "°C"
use_moon_phase_instead_of_clear_night = true
