[release]
download_release_url = ""

[api]
update_interval_mins = 60

# darwin = "qvv117"
# sydney = "r3gx2f"
# melbourne = "r1r0fs"
# brisbane = "ynGBTJ"
# perth = "r28ekz"
# adelaide = "r1f93c"
# hobart = "r22u0d"
# canberra = "r3dp32"
# tasmania-cold = "r283sf"
location = "r1r0fs" # uses GeoHash, must be 6 characters

# supproted colors = [black, white, green, blue, red, yellow, orange]
[colours]
background_colour = "white"
text_colour = "black"
x_axis_colour = "#74838f"
y_left_axis_colour = "#1f5079"
y_right_axis_colour = "#1b69a8"
temp_colour = "#ff0000"
feels_like_colour = "#00ff00"
rain_colour = "#0000ff"

[misc]
store_local = true
store_local_path = "./apis/"
template_path = "dashboard-template-min.svg"
modified_template_name = "dashboard.svg"
icon_path = "static/fill-svg-static/"
unit = "°C"
use_moon_phase_instead_of_clear_night = true
use_online_data = true # for debugging purposes
