[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
  "apt-get update",
  "DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes tzdata"
]

[build.env]
passthrough = [
    "RUN_MODE",
    "APP_API__PROVIDER",
    "RUSTFLAGS",
    "TZ",
]

# [target.x86_64-unknown-linux-gnu]
# pre-build = [
#     "dpkg --add-architecture $CROSS_DEB_ARCH",
#     "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
# ]

# [target.armv7-unknown-linux-gnueabihf]
# pre-build = [
#     "dpkg --add-architecture $CROSS_DEB_ARCH",
#     "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
# ]

# [target.aarch64-unknown-linux-gnu]
# pre-build = [
#     "dpkg --add-architecture $CROSS_DEB_ARCH",
#     "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
# ]
