[release]
release_info_url = "https://api.github.com/repos/mt-empty/pi-inky-weather-epd/releases/latest"
download_base_url = "https://github.com/mt-empty/pi-inky-weather-epd/releases/download"
# set to 0 to disable auto-updating
update_interval_days = 7

[api]
provider = "open_meteo"    # bom or open_meteo
latitude = -37.8136
longitude = 144.9631

# supported colours for 7.3 inky display
# [black, white, green, blue, red, yellow, orange]
[colours]
# background_colour   = "black"    # solid black – no dithering
# text_colour         = "white"    # bright white for max legibility

# x_axis_colour       = "white"   # high-contrast tick/label grid
# y_left_axis_colour  = "red"      # temperature axis
# y_right_axis_colour = "blue"     # matches rain scale

# actual_temp_colour  = "red"      # solid line for real temp
# feels_like_colour   = "green"    # dashed “feels-like” line
# rain_colour         = "blue"     # shaded rain bars

background_colour = "white"
text_colour = "black"
x_axis_colour = "black"
y_left_axis_colour = "red"
y_right_axis_colour = "blue"
actual_temp_colour = "red"
feels_like_colour = "green"
rain_colour = "blue"

[render_options]
temp_unit = "C"
# When the sky is clear, the moon phase icon will be used instead of the clear night icon
use_moon_phase_instead_of_clear_night = true
# this controls the placement of the x-axis when the temperature is below zero
x_axis_always_at_min = true
use_gust_instead_of_wind = false

[misc]
weather_data_cache_path = "./cached_bom_data/"
template_path = "dashboard-template-min.svg"
generated_svg_name = "dashboard.svg"
generated_png_name = "dashboard.png"
svg_icons_directory = "static/fill-svg-static/"

[debugging]
disable_weather_api_requests = false # if true, the weather data will be loaded from a cached file instead of the API, make you ran the application at least once with this set to false
disable_png_output = false
allow_pre_release_version = false
