[release]
release_info_url = "https://api.github.com/repos/mt-empty/pi-inky-weather-epd/releases/latest"
download_base_url = "https://github.com/mt-empty/pi-inky-weather-epd/releases/download"
# set to 0 to disable auto-updating
update_interval_days = 7

## Major Cities
# Darwin: "qvv117"
# Sydney: "r3gx2f"
# Melbourne: "r1r0fs"
# Brisbane: "r7hgd6"
# Perth: "r28ekz"
# Adelaide: "r1f93c"
# Hobart: "r22u0d"
# Canberra: "r3dp32"
[api]
location = "r3gx2f" # uses GeoHash, must be 6 characters

# supported colours for 7.3 inky display
# [black, white, green, blue, red, yellow, orange]
[colours]
background_colour = "white"
text_colour = "black"
x_axis_colour = "black"
y_left_axis_colour = "red"
y_right_axis_colour = "blue"
temp_colour = "red"
feels_like_colour = "green"
rain_colour = "blue"

[render_options]
temp_unit = "C"
# When the sky is clear, the moon phase icon will be used instead of the clear night icon
use_moon_phase_instead_of_clear_night = true
# this controls the placement of the x-axis when the temperature is below zero
x_axis_always_at_min = true

[misc]
weather_data_cache_path = "./cached_bom_data/"
template_path = "dashboard-template-min.svg"
generated_svg_name = "dashboard.svg"
generated_png_name = "dashboard.png"
svg_icons_directory = "static/fill-svg-static/"

[debugging]
disable_network_requests = false # if true, the weather data will be loaded from a cached file instead of the API, make you ran the application at least once with this set to false 
disable_png_output = false