## Extremes
# Babinda, QLD: "rhzv2d" # wettest place in Australia
# Marble Bar, NSW: "qgph8w" # hottest place in Australia
# Tasmanian heights, TAS: "r283sf" # coldest place in Tasmania 

## Major Cities
# Darwin: "qvv117"
# Sydney: "r3gx2f"
# Melbourne: "r1r0fs"
# Brisbane: "r7hgd6"
# Perth: "r28ekz"
# Adelaide: "r1f93c"
# Hobart: "r22u0d"
# Canberra: "r3dp32"
[api]
location = "r1r0fs" # uses GeoHash, must be 6 characters

[misc]
weather_data_store_path = "./src/apis/bom/samples/"
template_path = "dashboard-template-min.svg"
modified_template_name = "dashboard.svg"
generated_png_name = "dashboard.png"
svg_icons_directory = "static/fill-svg-static/"
python_script_path = "/home/dietpi/Pimoroni/inky/examples/7color/image.py"
python_path = "/home/dietpi/env/bin/python3"

[debugging]
disable_network_requests = false # if true, the weather data will be loaded from a cached file instead of the API, make you ran the application at least once with this set to false 
disable_png_output = false
disable_drawing_on_epd = true 