use crate::{CONFIG, NOT_AVAILABLE_ICON};
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Context {
    pub background_colour: String,
    pub text_colour: String,
    pub x_axis_colour: String,
    pub y_left_axis_colour: String,
    pub y_right_axis_colour: String,
    pub temp_colour: String,
    pub feels_like_colour: String,
    pub rain_colour: String,
    pub uv_max_today: String,
    pub max_wind_gust_today: String,
    pub max_relative_humidity_today: String,
    pub total_rain_today: String,
    pub temp_unit: String,
    pub current_temp: String,
    pub current_icon: String,
    pub current_feels_like: String,
    pub current_wind_speed: String,
    pub current_wind_icon: String,
    pub current_uv_index: String,
    pub current_relative_humidity: String,
    pub current_relative_humidity_icon: String,
    pub current_day_name: String,
    pub current_rain_amount: String,
    pub rain_measure_icon: String,
    pub graph_height: String,
    pub graph_width: String,
    pub temp_curve_data: String,
    pub feel_like_curve_data: String,
    pub rain_curve_data: String,
    pub uv_index: String,
    pub uv_index_icon: String,
    pub wind_speed: String,
    pub wind_icon: String,
    pub x_axis_path: String,
    pub x_axis_guideline_path: String,
    pub y_left_axis_path: String,
    pub x_labels: String,
    pub y_left_labels: String,
    pub y_right_axis_path: String,
    pub y_right_labels: String,
    pub uv_gradient: String,
    // daily forecast
    pub day2_mintemp: String,
    pub day2_maxtemp: String,
    pub day2_icon: String,
    pub day2_name: String,
    pub day3_mintemp: String,
    pub day3_maxtemp: String,
    pub day3_icon: String,
    pub day3_name: String,
    pub day4_mintemp: String,
    pub day4_maxtemp: String,
    pub day4_icon: String,
    pub day4_name: String,
    pub day5_mintemp: String,
    pub day5_maxtemp: String,
    pub day5_icon: String,
    pub day5_name: String,
    pub day6_mintemp: String,
    pub day6_maxtemp: String,
    pub day6_icon: String,
    pub day6_name: String,
    pub day7_mintemp: String,
    pub day7_maxtemp: String,
    pub day7_icon: String,
    pub day7_name: String,
    pub sunset_time: String,
    pub sunrise_time: String,
    pub sunset_icon: String,
    pub sunrise_icon: String,
    pub warning_message: String,
    pub warning_icon: String,
    pub warning_visibility: String,
}

impl Default for Context {
    fn default() -> Self {
        Self {
            background_colour: CONFIG.colours.background_colour.clone(),
            text_colour: CONFIG.colours.text_colour.clone(),
            x_axis_colour: CONFIG.colours.x_axis_colour.clone(),
            y_left_axis_colour: CONFIG.colours.y_left_axis_colour.clone(),
            y_right_axis_colour: CONFIG.colours.y_right_axis_colour.clone(),
            temp_colour: CONFIG.colours.temp_colour.clone(),
            feels_like_colour: CONFIG.colours.feels_like_colour.clone(),
            rain_colour: CONFIG.colours.rain_colour.clone(),
            uv_max_today: "NA".to_string(),
            max_wind_gust_today: "NA".to_string(),
            max_relative_humidity_today: "NA".to_string(),
            total_rain_today: "NA".to_string(),
            temp_unit: CONFIG.render_options.temp_unit.clone(),
            current_temp: "NA".to_string(),
            current_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            current_feels_like: "NA".to_string(),
            current_wind_speed: "NA".to_string(),
            current_wind_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            current_uv_index: "NA".to_string(),
            current_relative_humidity: "NA".to_string(),
            current_relative_humidity_icon: format!(
                "{}{}",
                CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON
            ),
            current_day_name: "NA".to_string(),
            current_rain_amount: "NA".to_string(),
            rain_measure_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            graph_height: "300".to_string(),
            graph_width: "600".to_string(),
            temp_curve_data: "".to_string(),
            feel_like_curve_data: "".to_string(),
            rain_curve_data: "".to_string(),
            uv_index: "NA".to_string(),
            uv_index_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            wind_speed: "NA".to_string(),
            wind_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            x_axis_path: "".to_string(),
            x_axis_guideline_path: "".to_string(),
            y_left_axis_path: "".to_string(),
            x_labels: "".to_string(),
            y_left_labels: "".to_string(),
            y_right_axis_path: "".to_string(),
            y_right_labels: "".to_string(),
            uv_gradient: "".to_string(),
            day2_mintemp: "NA".to_string(),
            day2_maxtemp: "NA".to_string(),
            day2_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day2_name: "NA".to_string(),
            day3_mintemp: "NA".to_string(),
            day3_maxtemp: "NA".to_string(),
            day3_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day3_name: "NA".to_string(),
            day4_mintemp: "NA".to_string(),
            day4_maxtemp: "NA".to_string(),
            day4_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day4_name: "NA".to_string(),
            day5_mintemp: "NA".to_string(),
            day5_maxtemp: "NA".to_string(),
            day5_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day5_name: "NA".to_string(),
            day6_mintemp: "NA".to_string(),
            day6_maxtemp: "NA".to_string(),
            day6_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day6_name: "NA".to_string(),
            day7_mintemp: "NA".to_string(),
            day7_maxtemp: "NA".to_string(),
            day7_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            day7_name: "NA".to_string(),
            sunrise_time: "NA".to_string(),
            sunset_time: "NA".to_string(),
            sunset_icon: format!("{}sunset.svg", CONFIG.misc.svg_icons_directory),
            sunrise_icon: format!("{}sunrise.svg", CONFIG.misc.svg_icons_directory),
            warning_message: "NA".to_string(),
            warning_icon: format!("{}{}", CONFIG.misc.svg_icons_directory, NOT_AVAILABLE_ICON),
            warning_visibility: "hidden".to_string(),
        }
    }
}
